language: python
python:
  - 2.7
  - 3.6
before_install:
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-remotedata
  - pip install sphinx_rtd_theme
  - pip install numpydoc
install:
  - pip install -r requirements.txt
# command to run tests
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# command to run tests
script:
  - pytest --remote-data

after_success:
  - codecov
